### ISSUE TITLE
SQLite failed creating table revision: unrecognized token: "'"

### ISSUE THREAD

**Issue by dresken** [techouse/mysql-to-sqlite3#34]
**Describe the bug**
When trying to convert a database, I receive an error about a quote character '. I thought it may be due to the character being a value in the table rows - however I updated this as a troubleshooting test - and still get the same error.

**Expected behaviour**
No Error

**Actual result**
2022-12-12 03:12:11 INFO     Transferring table revision
2022-12-12 03:12:11 ERROR    SQLite failed creating table revision: unrecognized token: "'"

**System Information**
| software               | version                              |
|------------------------|--------------------------------------|
| mysql-to-sqlite3       | 1.4.14                               |
|                        |                                      |
| Operating System       | Linux 5.15.64-0-virt                 |
| Python                 | CPython 2.7.18                       |
| MySQL                  | MySQL client not found on the system |
| SQLite                 | 3.30.1                               |
|                        |                                      |
| click                  | 7.1.2                                |
| mysql-connector-python | 8.0.23                               |
| python-slugify         | 4.0.1                                |
| pytimeparse            | 1.1.8                                |
| simplejson             | 3.18.0                               |
| six                    | 1.16.0                               |
| tabulate               | 0.8.5                                |
| tqdm                   | 4.64.1                               |

**Additional context**
Traceback (most recent call last):
  File "/usr/local/bin/mysql2sqlite", line 8, in <module>
2022-12-12 03:19:16 ERROR    SQLite failed creating table revision: unrecognized token: "'"
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/mysql_to_sqlite3/cli.py", line 183, in cli
    converter.transfer()
  File "/usr/local/lib/python2.7/site-packages/mysql_to_sqlite3/transporter.py", line 554, in transfer
    self._create_table(table_name)
  File "/usr/local/lib/python2.7/site-packages/mysql_to_sqlite3/transporter.py", line 409, in _create_table
    self._sqlite_cur.executescript(self._build_create_table_sql(table_name))
sqlite3.OperationalError: unrecognized token: "'"

**Comment by techouse** [comment]
Hmm, can you try running this with Python 3?

If it's still an issue, I'll need the database dump to replicate this error.

**Comment by dresken** [comment]
Sorry I had started with python3, but then switched to see if it was a version issue. Same error on 3. (see below)

The table names doesn't look to have quotes - it is an old MediaWiki database. DDL: [meadiocre_wiki.sql.txt](https://github.com/techouse/mysql-to-sqlite3/files/10207383/meadiocre_wiki.sql.txt)

2022-12-12 10:49:35 ERROR    SQLite failed creating table revision: unrecognized token: "'"
Traceback (most recent call last):
  File "/usr/local/bin/mysql2sqlite", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mysql_to_sqlite3/cli.py", line 183, in cli
    converter.transfer()
  File "/usr/local/lib/python3.10/site-packages/mysql_to_sqlite3/transporter.py", line 554, in transfer
    self._create_table(table_name)
  File "/usr/local/lib/python3.10/site-packages/mysql_to_sqlite3/transporter.py", line 409, in _create_table
    self._sqlite_cur.executescript(self._build_create_table_sql(table_name))
sqlite3.OperationalError: unrecognized token: "'"

**Comment by techouse** [comment]
Hah, my best guess at the moment is that it could be the `enum` table types.

I'll run some tests once I have some time.

**Comment by dresken** [comment]
Cheers heaps.

Probably one other thing I should mention is that some tables work before it gets to the fateful "revision" table and falls over
2022-12-12 11:09:17 INFO     Transferring table text
2022-12-12 11:09:17 INFO     Transferring table user_former_groups
2022-12-12 11:09:17 INFO     Transferring table page_props
2022-12-12 11:09:17 INFO     Transferring table site_stats
2022-12-12 11:09:17 INFO     Transferring table site_identifiers
2022-12-12 11:09:17 INFO     Transferring table categorylinks
2022-12-12 11:09:17 INFO     Transferring table uploadstash
2022-12-12 11:09:17 INFO     Transferring table watchlist
2022-12-12 11:09:17 INFO     Transferring table querycachetwo
2022-12-12 11:09:17 INFO     Transferring table transcache
2022-12-12 11:09:17 INFO     Transferring table imagelinks

**Comment by dresken** [comment]
I also just chucked in a print statement to get the value of sql before it is returned - other than a couple of strings (which seem correct) - there's no ' character in there. And pasted the SQL into sqlite and it worked by the looks. Weirder.

CREATE TABLE IF NOT EXISTS "revision" (
	"rev_id" INTEGER NOT NULL  ,
	"rev_page" INTEGER NOT NULL  ,
	"rev_text_id" INTEGER NOT NULL  ,
	"rev_comment" BLOB NOT NULL  ,
	"rev_user" INTEGER NOT NULL DEFAULT '0' ,
	"rev_user_text" BLOB NOT NULL DEFAULT '' ,
	"rev_timestamp" BLOB NOT NULL DEFAULT '' ,
	"rev_minor_edit" TINYINT NOT NULL DEFAULT '0' ,
	"rev_deleted" TINYINT NOT NULL DEFAULT '0' ,
	"rev_len" INTEGER NULL  ,
	"rev_parent_id" INTEGER NULL  ,
	"rev_sha1" BLOB NOT NULL DEFAULT '' ,
	"rev_content_model" BLOB NULL  ,
	"rev_content_format" BLOB NULL  ,
	PRIMARY KEY ("rev_id")
);CREATE  INDEX IF NOT EXISTS "page_timestamp" ON "revision" ("rev_page", "rev_timestamp");CREATE  INDEX IF NOT EXISTS "page_user_timestamp" ON "revision" ("rev_page", "rev_user", "rev_timestamp");CREATE  INDEX IF NOT EXISTS "rev_page_id" ON "revision" ("rev_page", "rev_id");CREATE  INDEX IF NOT EXISTS "rev_timestamp" ON "revision" ("rev_timestamp");CREATE  INDEX IF NOT EXISTS "usertext_timestamp" ON "revision" ("rev_user_text", "rev_timestamp");CREATE  INDEX IF NOT EXISTS "user_timestamp" ON "revision" ("rev_user", "rev_timestamp");

**Comment by dresken** [comment]
I created a copy database just from the DDL - and then dropped the revision table. It only got so far before encountering the same issue. The following tables also have the same issue reported when they exist.

- drop table revision;
- drop table user;
- drop table bot_passwords;
- drop table page;
- drop table archive;
- drop table oldimage;
- drop table filearchive;
- drop table ipblocks;

**Comment by dresken** [comment]
Good pick up - Interesting - I'm not sure how it comes through yet - the SHOW COLUMNS query that is used doesn't appear to show anything for a Default. But that could just be a display issue - might actually be data there. (Actually had a look in phpmyadmin - had to get right down to changing the column page - but it shows "��������������" as the value.

Seems to all come down to what the _translate_default_from_mysql_to_sqlite function does with that output. I think it doesn't have that the original column type was a BINARY type at that stage (looks to have changed it to BLOB). Creating a new MediaWiki using sqlite appears to create the column to BLOB default('') - so that appears to be the direction to head in for it. 

SHOW COLUMNS FROM revision;
+--------------------+---------------------+------+-----+----------------+----------------+
| Field              | Type                | Null | Key | Default        | Extra          |
+--------------------+---------------------+------+-----+----------------+----------------+
...
| rev_timestamp      | binary(14)          | NO   | MUL |                |                |
...
+--------------------+---------------------+------+-----+----------------+----------------+

**Comment by dresken** [comment]
Well I jammed this in to transporter.py - not sure it's quite the right solution (it's not dealing with null termination properly)- but it gets me on the path to getting my current task done.

        column_default = column_default.replace('\0', '')
        return "DEFAULT '{}'".format(column_default)

Cheers for your help

**Comment by techouse** [comment]
I'm not sure when I'll have time to properly look at this. Might be weeks before I do. In the meantime, if you fancy making a PR with tests I'd be very grateful. :)

**Comment by techouse** [comment]
Reading [this answer here](https://stackoverflow.com/questions/66964893/sqlite3-binary-data-type) explains it a bit. `BINARY` in SQLite terms has a `NUMERIC` affinity. Kinda tricky to work with.

**Comment by techouse** [comment]
Hmm, for me this transfer works normally.

```
2022-12-17 11:48:47 INFO     Transferring table archive
2022-12-17 11:48:47 INFO     Transferring table bot_passwords
2022-12-17 11:48:47 INFO     Transferring table category
2022-12-17 11:48:47 INFO     Transferring table categorylinks
2022-12-17 11:48:47 INFO     Transferring table change_tag
2022-12-17 11:48:47 INFO     Transferring table externallinks
2022-12-17 11:48:47 INFO     Transferring table filearchive
2022-12-17 11:48:47 INFO     Transferring table image
2022-12-17 11:48:47 INFO     Transferring table imagelinks
2022-12-17 11:48:47 INFO     Transferring table interwiki
2022-12-17 11:48:47 INFO     Transferring table ipblocks
2022-12-17 11:48:47 INFO     Transferring table iwlinks
2022-12-17 11:48:47 INFO     Transferring table job
2022-12-17 11:48:47 INFO     Transferring table l10n_cache
2022-12-17 11:48:47 INFO     Transferring table langlinks
2022-12-17 11:48:47 INFO     Transferring table log_search
2022-12-17 11:48:47 INFO     Transferring table logging
2022-12-17 11:48:47 INFO     Transferring table module_deps
2022-12-17 11:48:47 INFO     Transferring table objectcache
2022-12-17 11:48:47 INFO     Transferring table oldimage
2022-12-17 11:48:47 INFO     Transferring table page
2022-12-17 11:48:47 INFO     Transferring table page_props
2022-12-17 11:48:47 INFO     Transferring table page_restrictions
2022-12-17 11:48:47 INFO     Transferring table pagelinks
2022-12-17 11:48:47 INFO     Transferring table protected_titles
2022-12-17 11:48:47 INFO     Transferring table querycache
2022-12-17 11:48:47 INFO     Transferring table querycache_info
2022-12-17 11:48:47 INFO     Transferring table querycachetwo
2022-12-17 11:48:47 INFO     Transferring table recentchanges
2022-12-17 11:48:47 INFO     Transferring table redirect
2022-12-17 11:48:47 INFO     Transferring table revision
2022-12-17 11:48:47 INFO     Transferring table searchindex
2022-12-17 11:48:48 INFO     Transferring table site_identifiers
2022-12-17 11:48:48 INFO     Transferring table site_stats
2022-12-17 11:48:48 INFO     Transferring table sites
2022-12-17 11:48:48 INFO     Transferring table tag_summary
2022-12-17 11:48:48 INFO     Transferring table templatelinks
2022-12-17 11:48:48 INFO     Transferring table text
2022-12-17 11:48:48 INFO     Transferring table transcache
2022-12-17 11:48:48 INFO     Transferring table updatelog
2022-12-17 11:48:48 INFO     Transferring table uploadstash
2022-12-17 11:48:48 INFO     Transferring table user
2022-12-17 11:48:48 INFO     Transferring table user_former_groups
2022-12-17 11:48:48 INFO     Transferring table user_groups
2022-12-17 11:48:48 INFO     Transferring table user_newtalk
2022-12-17 11:48:48 INFO     Transferring table user_properties
2022-12-17 11:48:48 INFO     Transferring table valid_tag
2022-12-17 11:48:48 INFO     Transferring table watchlist
2022-12-17 11:48:48 INFO     Done!
```

This is what I get out [mediawiki.db.zip](https://github.com/techouse/mysql-to-sqlite3/files/10251613/mediawiki.db.zip)

**Comment by techouse** [comment]
@dresken is this still an issue?
