### ISSUE TITLE
unknown column "ERROR_NUMBER" in foreign key definition

### ISSUE THREAD

**Issue by dethrophes** [techouse/mysql-to-sqlite3#61]
https://github.com/techouse/mysql-to-sqlite3/blob/29ceb9f9a59856d86e8c42b1d8f538398a611a08/mysql_to_sqlite3/transporter.py#L450C1-L450C16

This query doesn't seem to be sufficient, on my setup it causes non existent FOREIGN COLUMN entries in the table creation sql.

```python
2023-12-31 19:24:43 ERROR    SQLite failed creating table owners: unknown column "ERROR_NUMBER" in foreign key definition
Traceback (most recent call last):
  File "/home/dethrophes/.local/bin/mysql2sqlite", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/dethrophes/.local/lib/python3.8/site-packages/mysql_to_sqlite3/cli.py", line 170, in cli
    converter.transfer()
  File "/home/dethrophes/.local/lib/python3.8/site-packages/mysql_to_sqlite3/transporter.py", line 614, in transfer
    self._create_table(table_name)  # type: ignore[arg-type]
  File "/home/dethrophes/.local/lib/python3.8/site-packages/mysql_to_sqlite3/transporter.py", line 484, in _create_table
    self._sqlite_cur.executescript(self._build_create_table_sql(table_name))
sqlite3.OperationalError: unknown column "ERROR_NUMBER" in foreign key definition
``` 
e.g.
![image](https://github.com/techouse/mysql-to-sqlite3/assets/1491187/37e28ac4-43a0-4eeb-992f-b0dc8d679e1c)

if I add this to the join  AND i.TABLE_NAME = k.TABLE_NAME 
```python
                SELECT k.COLUMN_NAME AS `column`,
                       k.REFERENCED_TABLE_NAME AS `ref_table`,
                       k.REFERENCED_COLUMN_NAME AS `ref_column`,
                       c.UPDATE_RULE AS `on_update`,
                       c.DELETE_RULE AS `on_delete`
                FROM information_schema.TABLE_CONSTRAINTS AS i
                {JOIN} information_schema.KEY_COLUMN_USAGE AS k
                    ON i.CONSTRAINT_NAME = k.CONSTRAINT_NAME  AND i.TABLE_NAME = k.TABLE_NAME 
                {JOIN} information_schema.REFERENTIAL_CONSTRAINTS AS c
                    ON c.CONSTRAINT_NAME = i.CONSTRAINT_NAME
                WHERE i.TABLE_SCHEMA = %s
                AND i.TABLE_NAME = %s
                AND i.CONSTRAINT_TYPE = %s
                GROUP BY i.CONSTRAINT_NAME,
                         k.COLUMN_NAME,
                         k.REFERENCED_TABLE_NAME,
                         k.REFERENCED_COLUMN_NAME,
                         c.UPDATE_RULE,
                         c.DELETE_RULE
``` 

then I no longer see the issue.
![image](https://github.com/techouse/mysql-to-sqlite3/assets/1491187/2594c5cf-b93c-479e-b1d5-bb9dc0b54dbc)

**Comment by techouse** [comment]
Hey,

Interesting issue. Could you please provide a DDL that caused this issue?
