### ISSUE TITLE
Cannot import name 'ToPythonOutputTypes' from 'mysql.connector.types'

### ISSUE THREAD

**Issue by makeevolution** [techouse/mysql-to-sqlite3#65]
**Describe the bug**
After downloading the package using pip and running it `mysql2sqlite --version`, I get the exception

```
Traceback (most recent call last):
  File "/usr/local/bin/mysql2sqlite", line 5, in <module>
    from mysql_to_sqlite3.cli import cli
  File "/usr/local/lib/python3.9/site-packages/mysql_to_sqlite3/__init__.py", line 4, in <module>
    from .transporter import MySQLtoSQLite
  File "/usr/local/lib/python3.9/site-packages/mysql_to_sqlite3/transporter.py", line 18, in <module>      
    from mysql.connector.types import ToPythonOutputTypes
ImportError: cannot import name 'ToPythonOutputTypes' from 'mysql.connector.types' (/usr/local/lib/python3.9/site-packages/mysql/connector/types.py)
```
I googled around but couldn't find anyone with similar issue

**Expected behaviour**
The version

**Actual result**
The above exception

**System Information**

```
python3.9
Red Hat Enterprise Linux 8.9 (Ootpa)
```

**Comment by techouse** [comment]
Hi,

Can you please follow the bug issue template's instructions and paste the whole output of `--version`?

**Comment by makeevolution** [comment]
Hi,

Running `mysql2sqlite --version` gives me the traceback

```
Traceback (most recent call last):
  File "/usr/local/bin/mysql2sqlite", line 5, in <module>
    from mysql_to_sqlite3.cli import cli
  File "/usr/local/lib/python3.9/site-packages/mysql_to_sqlite3/__init__.py", line 4, in <module>
    from .transporter import MySQLtoSQLite
  File "/usr/local/lib/python3.9/site-packages/mysql_to_sqlite3/transporter.py", line 18, in <module>      
    from mysql.connector.types import ToPythonOutputTypes
ImportError: cannot import name 'ToPythonOutputTypes' from 'mysql.connector.types' (/usr/local/lib/python3.9/site-packages/mysql/connector/types.py)
```

**Comment by techouse** [comment]
Most likely because the connector is too old. Can you get its version for me please?

**Comment by techouse** [comment]
Fixed in [v2.1.9](https://github.com/techouse/mysql-to-sqlite3/releases/tag/v2.1.9).

Thanks again for the bug report! <3
