### ISSUE TITLE
Protocol mismatch

### ISSUE THREAD

**Issue by blue-pinapple** [techouse/mysql-to-sqlite3#90]
**Describe the bug**
I get a protocol mismatch error when I try to run the command 
mysql2sqlite -f /Users/whale/Downloads/chinook.db (is this meant to be an existing file that gets overwritten?)   -d coreprotect -u avnadmin -h mysql-11185b2a-###.aivencloud.com -P 19875

**Expected behaviour**
It allows me to connect to the server 

**Actual result**
error with debug:
```mysql2sqlite version 2.3.0 Copyright (c) 2019-2024 Klemen Tusar
2024-11-22 16:32:59 ERROR    Protocol mismatch; server version = 11, client version = 10
Traceback (most recent call last):
  File "/opt/homebrew/bin/mysql2sqlite", line 8, in <module>
    sys.exit(cli())
             ~~~^^
  File "/opt/homebrew/Cellar/mysql-to-sqlite3/2.3.0/libexec/lib/python3.13/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/mysql-to-sqlite3/2.3.0/libexec/lib/python3.13/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/Cellar/mysql-to-sqlite3/2.3.0/libexec/lib/python3.13/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/mysql-to-sqlite3/2.3.0/libexec/lib/python3.13/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/Cellar/mysql-to-sqlite3/2.3.0/libexec/lib/python3.13/site-packages/mysql_to_sqlite3/cli.py", line 205, in cli
    converter = MySQLtoSQLite(
        sqlite_file=sqlite_file,
    ...<21 lines>...
        quiet=quiet,
    )
  File "/opt/homebrew/Cellar/mysql-to-sqlite3/2.3.0/libexec/lib/python3.13/site-packages/mysql_to_sqlite3/transporter.py", line 133, in __init__
    _mysql_connection = mysql.connector.connect(
        user=self._mysql_user,
    ...<5 lines>...
        collation=self._mysql_collation,
    )
  File "/opt/homebrew/Cellar/mysql-to-sqlite3/2.3.0/libexec/lib/python3.13/site-packages/mysql/connector/pooling.py", line 323, in connect
    return MySQLConnection(*args, **kwargs)
  File "/opt/homebrew/Cellar/mysql-to-sqlite3/2.3.0/libexec/lib/python3.13/site-packages/mysql/connector/connection.py", line 179, in __init__
    self.connect(**kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^
  File "/opt/homebrew/Cellar/mysql-to-sqlite3/2.3.0/libexec/lib/python3.13/site-packages/mysql/connector/abstracts.py", line 1399, in connect
    self._open_connection()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/opt/homebrew/Cellar/mysql-to-sqlite3/2.3.0/libexec/lib/python3.13/site-packages/mysql/connector/connection.py", line 360, in _open_connection
    self._do_handshake()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/homebrew/Cellar/mysql-to-sqlite3/2.3.0/libexec/lib/python3.13/site-packages/mysql/connector/connection.py", line 213, in _do_handshake
    handshake = self._protocol.parse_handshake(packet)
  File "/opt/homebrew/Cellar/mysql-to-sqlite3/2.3.0/libexec/lib/python3.13/site-packages/mysql/connector/protocol.py", line 459, in parse_handshake
    raise DatabaseError(
    ...<2 lines>...
    )
mysql.connector.errors.DatabaseError: Protocol mismatch; server version = 11, client version = 10
```

**System Information**

```bash
$ mysql2sqlite --version
```

```
| software               | version                              |
|------------------------|--------------------------------------|
| mysql-to-sqlite3       | 2.3.0                                |
|                        |                                      |
| Operating System       | Darwin 24.0.0                        |
| Python                 | CPython 3.13.0                       |
| MySQL                  | MySQL client not found on the system | (I attempted to install it but it didn't show up)
| SQLite                 | 3.47.0                               |
|                        |                                      |
| click                  | 8.1.7                                |
| mysql-connector-python | 9.0.0                                |
| python-slugify         | 8.0.4                                |
| pytimeparse2           | 1.7.1                                |
| simplejson             | 3.19.2                               |
| tabulate               | 0.9.0                                |
| tqdm                   | 4.66.5                               |
```

**Additional context**
I tested installing it on homebrew and on pip
In case of errors please run the same command with `--debug`. This option is only available on v1.4.12 or greater.

**Comment by techouse** [comment]
https://stackoverflow.com/questions/60195263/os-catalina-and-laravel-homestead-mysql-error-error-2007-hy000-protocol-mism
